fix: Handle just building for PRs.
zmkfirmware/zmk-docker pull request #12
Opened 2021-05-04 00:23 UTC by petejohanson

Tweaking the GH containers action so that:

* It conditionally signs in to the registries only if the tokens are set.
* Tweaks the push/cache-to for the `docker/build-push-action` to be
  conditional based on if a PR or not.

2021-05-05 09:28 UTC, innovaker commented
I authorised the associated job but it failed?
https://github.com/zmkfirmware/zmk-docker/actions/runs/811971525

2021-05-05 09:46 UTC, innovaker reviewed
Have I understood this correctly?

a) jobs only login to DH and GHCR if they have tokens available

b) dependabot has access to its own secrets:
- `DOCKER_HUB_NAMESPACE`
- `DOCKER_HUB_TOKEN`
- `DOCKER_HUB_USERNAME`

c) all jobs still *read* from the cache, so there shouldn't be any reinventing the wheel (rebuilding from scratch) unless the base image changes

d) only jobs which have access to tokens will push to the cache, which combined with (b) means:
 i) dependabot PRs still push to the cache to facilitate multistage
 ii) non-dependabot PRs will not multistage properly if they change any stage above `dev` or `build`

e) only jobs which aren't a `pull_request` cause the image to be pushed to docker hub

---

If so ...

f) how do we access candidate images from dependabot's builds for testing?

g) is there a way for us to enable some form of caching for multistage builds for third party PRs?

I haven't tested this on my fork yet but am keen to do so given the nuances of the workflow.

2021-05-05 22:10 UTC, petejohanson commented on .github/workflows/containers.yml
> +  zephyr-sdk-version: 0.12.3
Sorry, this snuck in accidentally. Definitely agree, not intended.

2021-05-05 22:15 UTC, petejohanson commented
> Have I understood this correctly?
> 
> a) jobs only login to DH and GHCR if they have tokens available

Correct.

> 
> b) dependabot has access to its own secrets:
> - `DOCKER_HUB_NAMESPACE`
> - `DOCKER_HUB_TOKEN`
> - `DOCKER_HUB_USERNAME`
> 

Yes, I have already set these up.

> c) all jobs still *read* from the cache, so there shouldn't be any reinventing the wheel (rebuilding from scratch) unless the base image changes

Correct.
> 
> d) only jobs which have access to tokens will push to the cache, which combined with (b) means:
>  i) dependabot PRs still push to the cache to facilitate multistage

Correct.

>  ii) non-dependabot PRs will not multistage properly if they change any stage above `dev` or `build`

Correct.

> 
> e) only jobs which aren't a `pull_request` cause the image to be pushed to docker hub
> 

Also correct.
> ---
> 
> If so ...
> 
> f) how do we access candidate images from dependabot's builds for testing?

Pull from the zmkfirmwaredependabot registry instead.

> 
> g) is there a way for us to enable some form of caching for multistage builds for third party PRs?

Not easily, and IMHO low priority.
> 
> I haven't tested this on my fork yet but am keen to do so given the nuances of the workflow.

2021-05-05 22:33 UTC, innovaker commented
> Pull from the zmkfirmwaredependabot registry instead.

h) Does ` push: ${{ github.event_name != "pull_request" }}`  not equal `false` for a dependabot PR?

2021-05-05 22:45 UTC, innovaker commented
i) What issues do you foresee with dependabot pushing its candidates to the main `zmkfirmware` docker hub repository, as long as it's running under its own credentials?  The only tag it would have would be its corresponding github SHA.

2021-05-06 02:46 UTC, petejohanson commented on .github/workflows/containers.yml
> +  zephyr-sdk-version: 0.12.3
Reverted or now. Will include in follow up PR.

2021-05-06 02:46 UTC, petejohanson commented on .github/workflows/containers.yml
> +        id: cache-to-url
Done.

2021-05-06 02:49 UTC, petejohanson commented
> > Pull from the zmkfirmwaredependabot registry instead.
> 
> h) Does ` push: ${{ github.event_name != "pull_request" }}` not equal `false` for a dependabot PR?

Good catch. Adjusted to instead do this conditioned on having the Docker Hub token.

2021-05-06 02:51 UTC, petejohanson commented
> i) What issues do you foresee with dependabot pushing its candidates to the main `zmkfirmware` docker hub repository, as long as it's running under its own credentials? The only tag it would have would be its corresponding github SHA.

I'm mainly concerned about future refactors missing/not considering impacts, and us accidentally pushing/tagging things in the main registry that should not have been.

Just in general, I really think PRs, from dependabot or otherwise, should *not* be given write access to the main registry, as a general precaution.

2021-05-06 02:55 UTC, petejohanson reviewed
@innovaker A summary of the latest updates for your review.

2021-05-06 02:55 UTC, petejohanson commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
@innovaker This is used to ensure the fallback `cache-from` is pulling from the main registry, for PRs.

2021-05-06 02:55 UTC, petejohanson commented on .github/workflows/containers.yml
> +      - name: Check registry environment
This is needed in order to effectively use secrets in the `if` conditions of future steps, since secrets themselves cannot be directly used there.

2021-05-06 02:55 UTC, petejohanson commented on Dockerfile
> +  && apt-get -y install --no-install-recommends \
Without this change, our Docker build in fact is failing today locally or in GH.

This is due to some packaging changes w/ libcurl between backports and main, AFAICT.

This is the first "burn the bridge" for moving to the newer SDK/Zephyr, since the newer CMake does not work w/ 2.4, but is required for 2.5. 

I don't see a way around this, witthout merging this with failing actions *anyways*. We'll just need not *tag* anything until we're ready to tag the 2.5 once it is all ready.

2021-05-06 14:19 UTC, innovaker requested changes

2021-05-06 14:19 UTC, innovaker commented on Dockerfile
> +  && apt-get -y install --no-install-recommends \
This looks like a dependency conflict within `curl` because we're sourcing `cmake` from `buster-backports` in the `common` stage above it.  This was introduced by 5de32f5d1803fc0f86b9fccdc268cc1d10a4b3ff because  `debian:stable-slim` = `buster` runs `cmake` 3.13.4-1 but ZMK's boilerplating requires `list(PREPEND)` which was introduced by `cmake` 3.15.x.

Did you run a ZMK test build within the resulting container?  I ran it with ZMK's `HEAD` and it fails on `cmake` as it was doing before 5de32f5d1803fc0f86b9fccdc268cc1d10a4b3ff.  See: https://github.com/innovaker/zmk/runs/2518820325

---

> since the newer CMake does not work w/ 2.4, but is required for 2.5

It doesn't?  Given that `buster-backports` is newer than `stable-slim`, IIRC we've always been running the latest `cmake` with Zephyr 2.4?

---

My preferred fix for this is to bump `curl` to the `buster-backports` version until `bullseye` is released into stable, especially given that it's already under hard-freeze.  AFAIK, `curl` is only needed for downloading the `nodejs` installer so there shouldn't be any impact.

PR: https://github.com/zmkfirmware/zmk-docker/pull/13

I've tested it with `dependabot/docker/debian-stable-20210408-slim` rebased on top:
https://github.com/innovaker/zmk/actions/runs/817039626
which suggests it shouldn't cause a problem.

So I don't think this will be a problem for building the intermediary releases.  It's just needs a prerequisite workaround for `curl` that should go in before this current PR and everything else planned.

---

I think this also highlights the need for integrating Zephyr test builds into the container workflow, as touched on when we launched `zmk-docker`.

2021-05-06 14:19 UTC, innovaker commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub::${{ toJSON(secrets.DOCKER_HUB_TOKEN != null) }}'
That's a neat trick with `toJSON` and `fromJSON` - this was new to me!

I presume it sidesteps the extra boilerplate required to achieve the same via shell syntax?

2021-05-06 14:23 UTC, petejohanson commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
But it's not the token itself, it's the "do I have access" boolean, which we do to be safe and not accidentally leak the actual token in any output.

Perhaps `ghcr-access` or somesuch?

2021-05-06 14:24 UTC, petejohanson commented on .github/workflows/containers.yml
> +      - uses: haya14busa/action-cond@v1
I don't particularly care. Using a prebuilt action for the docker stuff seems better to me, rather than re-inventing the wheel, which is why I went this route.

2021-05-06 14:25 UTC, petejohanson commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub::${{ toJSON(secrets.DOCKER_HUB_TOKEN != null) }}'
Yes, and it gets you a true *boolean* for the conditionals, not the string `'false'` or `'true'`.

2021-05-06 16:50 UTC, innovaker commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
Given the way it's used in the `if` guards, it might be clearer with something along the lines of ...
- `ghcr-token-set`
- `is-ghcr-token-set`
- `ghcr-token-available`
- `is-ghcr-token-available`
- `ghcr-token-not-null`

Just spitballing for ideas.

2021-05-06 17:57 UTC, petejohanson commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
How about `perform-ghcr-updates` or `ghcr-write-access`?

2021-05-06 17:59 UTC, petejohanson commented on .github/workflows/containers.yml
> +        id: registry-access
Yeah, even with the other ongoing discussions, I like this better. Updated.

2021-05-06 17:59 UTC, petejohanson commented on .github/workflows/containers.yml
> +      - uses: haya14busa/action-cond@v1
Yeah, that's fair. Let me consider this one.

2021-05-06 18:22 UTC, innovaker commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
I think I prefer `ghcr-write-access` out of the two.  Combining the two lines of thought ...
- `has-ghcr-write-access`

and my personal favourite so far ...
- `ghcr-token-exists`

2021-05-06 18:54 UTC, petejohanson commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
I'm good w/ `ghcr-token-exists`. Will do.

2021-05-06 19:54 UTC, innovaker commented
Thanks for testing non-dependabot PR's with me @petejohanson: https://github.com/petejohanson/zmk-docker/pull/1

At least it builds them without failing even if it can't push candidates out to Docker Hub due to the security policy.

I guess the best way for us to create and test candidate images of non-dependabot PRs will be via our forks.
i.e. taking my account as an example ...
1. pull PR from https://github.com/zmkfirmware/zmk-docker to local
2. push PR from local to https://github.com/innovaker/zmk-docker
   - assuming tokens are configured, this will push a candidate to Docker Hub's `innovaker/zmk-build-arm:<hash>` and `innovaker/zmk-dev-arm:<hash>`
3. create local test branch for these images by modifying zmk's 3 references (search for `zmkfirmware/zmk-`)
4. push test branch to https://github.com/innovaker/zmk
5. ask #testing to play with the branch
6. discuss any issues on the original PR
7. merge the original PR when ready

It's not perfect.  It still sidesteps the main cache we *could* potentially lead to differences between the test build and the release build.  But it's the most secure of the options and beats doing it locally (which limits the potential testers).

At least `build` and `dev` will still be released simultaneously and therefore be consistent with one another - which is the primary goal.

2021-05-06 20:09 UTC, innovaker commented
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md

Going forward, I think it's time to revisit the `GitHub cache`.  I discarded it during initial development of `zmk-docker` in favour of `Registry cache`  but I don't remember why.  It could've been that it didn't work properly or maybe I wasn't using it properly.

If we can make it work, I think it would let us leverage the cache for all PRs (without credentials!).  It's still not ideal, but it would be one less hurdle.

2021-05-06 20:28 UTC, innovaker commented
https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md

Going forward, I think it's time to revisit the `GitHub cache`.  I *think* I discarded it during initial development of `zmk-docker` in favour of `Registry cache`  because each job in the matrix has a different runner and thus a different (fresh) local cache.  This invalidates the whole design approach ("build-only-once" mantra).

But I have a feeling we can work around this with [actions/upload-artifact](https://github.com/actions/upload-artifact) and [actions/download-artifact](https://github.com/actions/download-artifact) between the jobs.

If we can make it work, I think it would let us leverage the cache for all PRs (without credentials!).  It's still not ideal, but it would be one less source of inconsitency.

2021-05-06 20:31 UTC, petejohanson commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
Done.

2021-05-06 21:06 UTC, innovaker commented
Going forward I think we should consider `zmkfirmware-candidates` or `zmkfirmware-staging` instead of `zmkfirmwaredependabot` as the dumping ground for any candidate image (tagged only with the associated GH SHA) - including dependabot.  This would make the `zmkfirmware` namespace cleaner for unsuspecting users of the container images as well as provide a bit more security.  Thoughts?

2021-05-07 14:18 UTC, petejohanson commented on .github/workflows/containers.yml
> +      - uses: haya14busa/action-cond@v1
Ok, I found a way to do this without this random third party action, using a quasi-tertiary and the `format` function. I've removed the use of this action, and just tweaked how we set the docker action parameters.

2021-05-07 14:54 UTC, innovaker reviewed
Thanks @petejohanson!

The `cache-from`, `cache-to` is obviously quite dense but I think it's fine for our purposes.

How much testing have you put this through?
- Has it gone through a full test cycle?
    - send new PR to branch
    - check logs (uses existing cache appropriately)
    - test build running within candidate image
    - tag = release
    - check logs only involve cache retrieval and tagging
    - test build running within release image
 - Has it been tested with each secret removed or incorrectly entered?

2021-05-07 14:54 UTC, innovaker commented on .github/workflows/containers.yml
> +          echo '::set-output name=docker-hub-namespace::${{ secrets.DOCKER_HUB_NAMESPACE || 'zmkfirmware' }}'
No traction? 😄

2021-05-14 20:50 UTC, petejohanson commented
Superseded by #24

2021-05-14 20:50 UTC, closed without merging