feat(dev): add less (and set as default pager)
zmkfirmware/zmk-docker pull request #52
Opened 2021-05-20 18:57 UTC by innovaker

Requested by @mcrosson for flexibility.

2021-06-09 00:15 UTC, petejohanson requested changes
A thought on where we introduce this.

2021-06-09 00:32 UTC, mcrosson commented on Dockerfile
> +ENV PAGER=less
IMIO this should stay at the top ; it's adjusting the environment same as the LC on the line above and it shouldn't change often, if ever. The only time it should/would change is if something de-thrones less and is included as part of coreutils in Ubuntu. The only time cache would be invalidated is if this ENV definition changes.

On top of that it's high enough up that any follow on images / snapshots will have a consistent environment from the moment we make our adjustments through the end. I know I wouldn't be happy if I go to test or develop and my pager is suddenly 'more' instead of 'less' suddenly.

2021-06-09 21:11 UTC, innovaker commented on Dockerfile
> +ENV PAGER=less
The layers that depend on it are:
 - the `RUN` directly below
 - the `ENV DEBIAN_FRONTEND=`
 - `FROM dev-generic AS dev` (final stage)

The `RUN` is the most likely to change.

The potential benefits to cache consistency will shortly be superseded by #66.

That said, it might make a difference to anyone overriding it for a Docker build via CLI.  But it could be argued that they should be using `FROM` plus an override definition instead (which is more repeatable).

Thoughts?

2021-06-10 20:56 UTC, petejohanson commented on Dockerfile
> +ENV PAGER=less
It's certainly minor. I'm not stressed about it.

2021-06-10 20:56 UTC, petejohanson approved these changes

2021-06-12 19:20 UTC, merged